[build]
publish = "public"
command = "zola build"

[build.environment]
# Specify the Zola version you want to use
ZOLA_VERSION = "0.21.0" # Replace with your desired version

[dev]
# 1. This specifically disables the auto-detection that is confusing Hugo/Zola
framework = "#custom"

# 2. This command allows Netlify to run a preview server if needed
command = "zola serve --interface 0.0.0.0 --port 8888"

# 3. Match the port above
port = 8888
publish = "public"
